name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: php-actions/composer@v4
      - name: Install dependencies
        uses: php-actions/composer@v4
      - name: Run quality tools
        run:
          make check
